services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app/backend
    depends_on:
      - mongo
    restart: always

  mongo:
    container_name: mongo
    image: mongo:4.2.0
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    restart: always
