openapi: "3.0.0"
info:
  title: "Ochio Club API"
  version: "1.0.0"
  description: "API para el proyecto Ochio Club"
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"
servers:
  - url: "https://api.ochio-club.com"
paths:
  /users:
    get:
      operationId: "getUsers"
      summary: "Obtener lista de usuarios"
      responses:
        "200":
          description: "Lista de usuarios"
        "400":
          description: "Solicitud inválida"
      security:
        - apiKeyAuth: []
components:
  schemas:
    User:
      type: "object"
      properties:
        id:
          type: "string"
        name:
          type: "string"
        email:
          type: "string"
  securitySchemes:
    apiKeyAuth:
      type: "apiKey"
      in: "header"
      name: "Authorization"
