openapi: 3.0.0
info:
  title: OchioClub API
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.ochioclub.com
    description: Servidor principal
  - url: https://dev.ochioclub.com
    description: Servidor de desarrollo
tags:
  - name: users
    description: Operaciones de usuario
paths:
  /users:
    post:
      tags:
        - users
      summary: Crear usuario
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "201":
          description: Usuario creado
        "400":
          description: Datos inválidos
      security:
        - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
